# Pipeline to deploy goshop services & infrastructure

name: deployAzureResources

trigger:
- master

variables:
  serviceConnection: 'Azure CXP FTA Internal Subscription CBELLEE (b2375b5f-8dab-4436-b87c-32bc7fdce5d0)'
  location: australiaeast
  project: goshop
  acrResourceGroupName: $(project)-acr-rg
  containerName: 'templates'
  timeStamp: $[format('{0:yyyy}-{0:MM}-{0:dd}-{0:HHmmss}', pipeline.startTime)]
  aksVersion: 1.14.7
  aksNodeCount: 1
  maxPods: 50
  aksMinNodeCount: 1
  aksMaxNodeCount: 5
  aksNodeVMSize: Standard_F2s_v2

stages:
- stage: 'build'
  displayName: 'build stage'
  jobs:
    - job: 'acr_create_job'
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - task: AzureResourceGroupDeployment@2
          name: 'deploy_acr'
          displayName: 'Deploy Azure Container Registry'
          enabled: true
          inputs:
            action: Create Or Update Resource Group
            azureSubscription: $(serviceConnection)
            resourceGroupName: $(acrResourceGroupName)
            csmFile: ./infra/templates/nested/acr.json
            location: $(location)
            templateLocation: Linked artifact
            deploymentMode: Incremental
            deploymentName: "acrDeployment-$(timeStamp)"
            outputVariable: acrTemplateOutput
        
        - task: ARM Outputs@5
          name: 'acr_deployment_output'
          displayName: 'Get ACR Deployment Output'
          enabled: true
          inputs:
            ConnectedServiceNameSelector: 'ConnectedServiceNameARM'
            ConnectedServiceNameARM: $(serviceConnection)
            resourceGroupName: $(acrResourceGroupName)
            whenLastDeploymentIsFailed: 'fail'
            deploymentNameFilter: "acrDeployment-$(timeStamp)"

        - script:  echo "##vso[task.setvariable variable=acrName;isOutput=true]$(registryName)"
          name: acr_job_output

    - job: 'customer_api_container_build_job'
      dependsOn: 'acr_create_job'
      variables:
        acrName: $[dependencies.acr_create_job.outputs['acr_job_output.acrName']]
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - task: PowerShell@2
          inputs:
            targetType: inline
            script: |
              dir env:
          
        - task: AzureCLI@1
          displayName: 'Build customer api container image in ACR'
          enabled: true
          inputs:
            azureSubscription: $(serviceConnection)
            scriptLocation: inlineScript
            inlineScript: az acr build --image $(Build.Repository.Name) --registry $(acrName) --file ./api/customer/Dockerfile ./api/customer

    - job: 'product_api_container_build_job'
      dependsOn: 'acr_create_job'
      variables:
        acrName: $[dependencies.acr_create_job.outputs['acr_job_output.acrName']]
      pool:
        vmImage: 'ubuntu-latest'
      steps:    
        - task: AzureCLI@1
          displayName: 'Build product api container image in ACR'
          enabled: true
          inputs:
            azureSubscription: $(serviceConnection)
            scriptLocation: inlineScript
            inlineScript: az acr build --image $(Build.Repository.Name) --registry $(acrName) --file ./api/product/Dockerfile ./api/product

    - job: 'order_api_container_build_job'
      dependsOn: 'acr_create_job'
      variables:
        acrName: $[dependencies.acr_create_job.outputs['acr_job_output.acrName']]
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - task: AzureCLI@1
          displayName: 'Build order api container image in ACR'
          enabled: true
          inputs:
            azureSubscription: $(serviceConnection)
            scriptLocation: inlineScript
            inlineScript: az acr build --image $(Build.Repository.Name) --registry $(acrName) --file ./api/order/Dockerfile ./api/order

    - job: 'angular_container_build_job'
      dependsOn: 'acr_create_job'
      variables:
        acrName: $[dependencies.acr_create_job.outputs['acr_job_output.acrName']]
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - task: AzureCLI@1
          displayName: 'Build Angular ui container image in ACR'
          enabled: true
          inputs:
            azureSubscription: $(serviceConnection)
            scriptLocation: inlineScript
            inlineScript: az acr build --image $(Build.Repository.Name) --registry $(acrName) --file ./ui/Dockerfile ./ui

- stage: 'dev'
  displayName: 'dev release'
  variables:
    environmentName: dev
    projectName: $(environmentName)-aks
    resourceGroupName: "$(projectName)-rg"
    tags: '{"costCentre":"478132","project":"$(projectName)"}'
  jobs:
    - deployment: 
      pool:
        vmImage: 'ubuntu-latest'
      environment: $(environmentName)
      strategy:
       runOnce:
        deploy:
          steps:
          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: |
                $now = Get-Date
                $sasTokenExpiry = $now.AddHours(2).ToString('u') -replace ' ','T'
                Write-Host "##vso[task.setvariable variable=sasTokenExpiry;]$sasTokenExpiry"
          - task: AzureResourceGroupDeployment@2
            name: 'DeployStorage'
            displayName: 'Deploy storage account for arm templates'
            enabled: true
            inputs:
              action: Create Or Update Resource Group
              azureSubscription: $(serviceConnection)
              resourceGroupName: $(resourceGroupName)
              csmFile: ./infra/templates/nested/storage.json
              location: $(location)
              templateLocation: Linked artifact
              deploymentMode: Incremental
              deploymentName: "storageDeployment-$(timeStamp)"
              overrideParameters: -sasTokenExpiry $(sasTokenExpiry) -storageSku Standard_LRS -storageKind StorageV2 -tags $(tags) -containerName $(containerName)

          - task: ARM Outputs@5
            name: 'GetStorageDeploymentOutput'
            displayName: 'Get ARM Storage Deployment Output'
            enabled: true
            inputs:
              ConnectedServiceNameSelector: 'ConnectedServiceNameARM'
              ConnectedServiceNameARM: $(serviceConnection)
              resourceGroupName: $(resourceGroupName)
              whenLastDeploymentIsFailed: 'fail'
              deploymentNameFilter: "storageDeployment-$(timeStamp)"

          - task: AzureCLI@1
            displayName: 'Copy ARM template files to Azure blob storage'
            enabled: true
            inputs:
              azureSubscription: $(serviceConnection)
              scriptLocation: 'inlineScript'
              inlineScript: 'az storage blob upload-batch -d $(containerName) -s ./infra/templates/nested/ --pattern *.json --account-name $(storageAccountName)'
      
          - task: AzureResourceGroupDeployment@2
            name: 'deployResources'
            displayName: 'Deploy resources'
            enabled: true
            inputs:
              action: Create Or Update Resource Group
              azureSubscription: $(serviceConnection)
              resourceGroupName: $(resourceGroupName)
              csmFile: ./templates/azuredeploy.json
              csmParametersFile: ./templates/azuredeploy.parameters.json
              location: $(location)
              templateLocation: Linked artifact
              deploymentMode: Incremental
              deploymentName: "resourceDeployment-$(timeStamp)"
              overrideParameters: 
                -aksMinNodeCount $(aksMinNodeCount)
                -aksMaxNodeCount $(aksMaxNodeCount)
                -storageUri $(storageContainerUri)
                -sasToken $(storageAccountSasToken)
                -aksVersion $(aksVersion)
                -aksNodeCount $(aksNodeCount)
                -aksNodeVMSize $(aksNodeVMSize)
                -maxPods $(maxPods)
                -outboundIpCount 2
                #-aksServicePrincipalObjectId $(aksServicePrincipalObjectId)
                #-aksServicePrincipalAppId $(aksServicePrincipalAppId)
                #-aksServicePrincipalSecret $(aksServicePrincipalSecret)
          - task: ARM Outputs@5
            name: 'GetResourceDeploymentOutput'
            displayName: 'Get ARM Resource Deployment Output'
            enabled: true
            inputs:
              ConnectedServiceNameSelector: 'ConnectedServiceNameARM'
              ConnectedServiceNameARM: $(serviceConnection)
              resourceGroupName: $(resourceGroupName)
              whenLastDeploymentIsFailed: 'fail'
              deploymentNameFilter: "resourceDeployment-$(timeStamp)"
          - task: HelmInstaller@1
            displayName: 'Install Helm'
            enabled: false
          - task: AzureCLI@1
            displayName: 'Install Istio'
            enabled: false
            inputs:
              azureSubscription: $(serviceConnection)
              scriptLocation: scriptPath
              scriptPath: ./scripts/install-istio.sh
              arguments: -r $(resourceGroupName) -n $(aksName)
          - task: AzureCLI@1
            displayName: 'Install Voting App'
            enabled: false
            inputs:
              azureSubscription: $(serviceConnection)
              scriptLocation: scriptPath
              scriptPath: ./scripts/install-apps.sh
- stage: 'test'
  displayName: 'test environment release'
  variables:
    environmentName: test
    projectName: aks-$(environmentName)
    resourceGroupName: "$(projectName)-rg"
    tags: '{"costCentre":"478132","project":"$(projectName)"}'
  jobs:
    - deployment: 
      pool:
        vmImage: 'ubuntu-latest'
      environment: test-$(environmentName)-environment
      strategy:
       runOnce:
        deploy:
          steps:
          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: |
                $now = Get-Date
                $sasTokenExpiry = $now.AddHours(2).ToString('u') -replace ' ','T'
                Write-Host "##vso[task.setvariable variable=sasTokenExpiry;]$sasTokenExpiry"
          - task: AzureResourceGroupDeployment@2
            name: 'DeployStorage'
            displayName: 'Deploy storage account for arm templates'
            enabled: true
            inputs:
              action: Create Or Update Resource Group
              azureSubscription: $(serviceConnection)
              resourceGroupName: $(resourceGroupName)
              csmFile: ./templates/nested/storage.json
              location: $(location)
              templateLocation: Linked artifact
              deploymentMode: Incremental
              deploymentName: "storageDeployment-$(timeStamp)"
              overrideParameters: -sasTokenExpiry $(sasTokenExpiry) -storageSku Standard_LRS -storageKind StorageV2 -tags $(tags) -containerName $(containerName)
          - task: ARM Outputs@5
            name: 'GetStorageDeploymentOutput'
            displayName: 'Get ARM Storage Deployment Output'
            enabled: true
            inputs:
              ConnectedServiceNameSelector: 'ConnectedServiceNameARM'
              ConnectedServiceNameARM: $(serviceConnection)
              resourceGroupName: $(resourceGroupName)
              whenLastDeploymentIsFailed: 'fail'
              deploymentNameFilter: "storageDeployment-$(timeStamp)"
          - task: AzureCLI@1
            displayName: 'Copy ARM template files to Azure blob storage'
            enabled: true
            inputs:
              azureSubscription: $(serviceConnection)
              scriptLocation: 'inlineScript'
              inlineScript: 'az storage blob upload-batch -d $(containerName) -s ./infra/templates/nested/ --pattern *.json --account-name $(storageAccountName)'
          - task: AzureResourceGroupDeployment@2
            name: 'deployResources'
            displayName: 'Deploy resources'
            enabled: true
            inputs:
              action: Create Or Update Resource Group
              azureSubscription: $(serviceConnection)
              resourceGroupName: $(resourceGroupName)
              csmFile: ./templates/azuredeploy.json
              csmParametersFile: ./infra/templates/azuredeploy.parameters.json
              location: $(location)
              templateLocation: Linked artifact
              deploymentMode: Incremental
              deploymentName: "resourceDeployment-$(timeStamp)"
              overrideParameters: 
                -aksMinNodeCount $(aksMinNodeCount)
                -aksMaxNodeCount $(aksMaxNodeCount)
                -storageUri $(storageContainerUri)
                -sasToken $(storageAccountSasToken)
                -aksVersion $(aksVersion)
                -aksNodeCount $(aksNodeCount)
                -aksNodeVMSize $(aksNodeVMSize)
                -maxPods $(maxPods)
                -outboundIpCount 2
                #-aksServicePrincipalObjectId $(aksServicePrincipalObjectId)
                #-aksServicePrincipalAppId $(aksServicePrincipalAppId)
                #-aksServicePrincipalSecret $(aksServicePrincipalSecret)
          - task: ARM Outputs@5
            name: 'GetResourceDeploymentOutput'
            displayName: 'Get ARM Resource Deployment Output'
            enabled: true
            inputs:
              ConnectedServiceNameSelector: 'ConnectedServiceNameARM'
              ConnectedServiceNameARM: $(serviceConnection)
              resourceGroupName: $(resourceGroupName)
              whenLastDeploymentIsFailed: 'fail'
              deploymentNameFilter: "resourceDeployment-$(timeStamp)"
          - task: HelmInstaller@1
            displayName: 'Install Helm'
            enabled: false
          - task: AzureCLI@1
            displayName: 'Install Istio'
            enabled: false
            inputs:
              azureSubscription: $(serviceConnection)
              scriptLocation: scriptPath
              scriptPath: ./scripts/install-istio.sh
              arguments: -r $(resourceGroupName) -n $(aksName)
          - task: AzureCLI@1
            displayName: 'Install Voting App'
            enabled: false
            inputs:
              azureSubscription: $(serviceConnection)
              scriptLocation: scriptPath
              scriptPath: ./scripts/install-apps.sh