apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderapi
  template:
    metadata:
      labels:
        app: orderapi
    spec:
      containers:
      - name: orderapi
        image: "{{ .Values.registryName }}/{{ .Values.orderServiceImageName }}:{{ .Values.orderServiceVersion }}"
        command: ["./orderService"]
        args: ["serve"]
        env:
        - name: APP_DB_PASSWORD
          value: {{ .Values.global.cosmosDbPassword }}
        - name: APP_DB_NAME
          value: {{ .Values.global.cosmosDbName }}
        - name: APP_DB_HOST_SUFFIX
          value: {{ .Values.global.cosmosDbHostSuffix }}
        - name: APP_DB_HOST_NAME
          value: {{ .Values.global.cosmosDbHostName }}
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: acr-auth
        