apiVersion: apps/v1
kind: Deployment
metadata:
  name: customerapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customerapi
  template:
    metadata:
      labels:
        app: customerapi
    spec:
      containers:
      - name: customerapi
        image: "{{ .Values.registryName }}/{{ .Values.customerServiceImageName }}:{{ .Values.customerServiceVersion }}"
        command: ["./customerService"]
        args: ["serve"]
        env:
        - name: APP_DB_PASSWORD
          value: {{ .Values.global.cosmosDbPassword }}
        - name: APP_DB_NAME
          value: {{ .Values.global.cosmosDbName }}
        - name: APP_DB_HOST_SUFFIX
          value: {{ .Values.global.cosmosDbHostSuffix }}
        - name: APP_DB_HOST_NAME
          value: {{ .Values.global.cosmosDbHostName }}
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: acr-auth
        