name: customer_api_CI

trigger:
  paths:
    include:
      - ./api/customer

variables:
- group: goshop-variable-group

stages:
  - stage: 
    condition: 
    jobs:
      - job: 'customer_api_container_build_job'
        #dependsOn: 'acr_create_job'
          #acrName: $[dependencies.acr_create_job.outputs['acr_job_output.acrName']]
        pool:
          vmImage: 'ubuntu-latest'
        steps:          
          - task: AzureCLI@1
            displayName: 'Build customer api container image in ACR'
            enabled: true
            inputs:
              azureSubscription: $(serviceEndpoint)
              scriptLocation: inlineScript
              inlineScript: az acr build --image $(Build.Repository.Name)_customer_api:$(Build.SourceVersion) --registry $(acrName) --file ./api/customer/Dockerfile ./api/customer
  