name: customer_service_CI

trigger:
  paths:
    include:
      - ./api/customer

stages:
  - stage: 
    condition: 
    jobs:
      - job: 'customer_api_container_build_job'
        #dependsOn: 'acr_create_job'
          #acrName: $[dependencies.acr_create_job.outputs['acr_job_output.acrName']]
        pool:
          vmImage: 'ubuntu-latest'
        steps:          
          - task: AzureCLI@1
            displayName: 'Build customer api container image in ACR'
            enabled: true
            inputs:
              azureSubscription: 'Azure CXP FTA Internal Subscription CBELLEE (b2375b5f-8dab-4436-b87c-32bc7fdce5d0)'
              scriptLocation: inlineScript
              inlineScript: az acr build --image $(Build.Repository.Name) --registry $(acrName) --file ./api/customer/Dockerfile ./api/customer
  