name: product_service_CI

variables:
- group: goshop-variable-group

trigger:
  paths:
    include:
      - ./api/product

stages:
  - stage: 
    condition: 
    jobs:
      - job: 'product_api_container_build_job'
        #dependsOn: 'acr_create_job'
          #acrName: $[dependencies.acr_create_job.outputs['acr_job_output.acrName']]
        pool:
          vmImage: 'ubuntu-latest'
        steps:          
          - task: AzureCLI@1
            displayName: 'Build product api container image in ACR'
            enabled: true
            inputs:
              azureSubscription: 'Azure CXP FTA Internal Subscription CBELLEE (b2375b5f-8dab-4436-b87c-32bc7fdce5d0)'
              scriptLocation: inlineScript
              inlineScript: az acr build --image $(Build.Repository.Name)_product:$(Build.SourceVersion) --registry $(acrName) --file ./api/product/Dockerfile ./api/product
  