apiVersion: apps/v1
kind: Deployment
metadata:
  name: productapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productapi
  template:
    metadata:
      labels:
        app: productapi
    spec:
      containers:
      - name: productapi
        image: "{{ .Values.registryName }}/{{ .Values.productServiceImageName }}:{{ .Values.productServiceVersion }}"
        command: ["./productService"]
        args: ["serve"]
        env:
        - name: APP_DB_PASSWORD
          value: {{ .Values.cosmosDbPassword }}
        - name: APP_DB_NAME
          value: {{ .Values.cosmosDbName }}
        - name: APP_DB_HOST_SUFFIX
          value: {{ .Values.cosmosDbHostSuffix }}
        - name: APP_DB_HOST_NAME
          value: {{ .Values.cosmosDbHostName }}
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: acr-auth
        